export { StarRating } from './deprecated/StarRating/StarRating';
export { Overlay } from './deprecated/Overlay/Overlay';
export type { ListBoxItem } from './deprecated/Popups/ListBox/ListBox';
export { Select } from './deprecated/Select/ui/Select';
export { Code } from './deprecated/Code/Code';
export { Skeleton } from './deprecated/Skeleton/Skeleton';
export { Input } from './deprecated/Input/Input';
export { Portal } from './deprecated/Portal/Portal';
export { Modal } from './deprecated/Modal/Modal';
export { Loader } from './deprecated/Loader/Loader';
