name: linting, testing, building

on:
  push:
    branches:
      - main
      - dev
      - ci-cd
  pull_request:
    branches:
      - main
      - dev
      - ci-cd
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci

      # - name: build production project
      #   run: npm run build:prod
      # - name: linting ts
      #   run: npm run lint:ts
      # - name: linting css
      #   run: npm run lint:scss
      # - name: unit testing
      #   run: npm run test:unit
      - name: build storybook
        run: npm run sb:build
      - name: screenshot test
        run: npm run test:ui:ci
